<?php

namespace App\Helper\Shared;

class ValidateRequest
{
    public static function messages()
    {
        return [
            'accepted'             => __('The (%:attribute%) field must be accepted.'),
            'accepted_if'          => __('The (%:attribute%) field must be accepted when (%:other%) is (:value).'),
            'active_url'           => __('The (%:attribute%) field must be a valid URL.'),
            'after'                => __('The (%:attribute%) field must be a date after (:date).'),
            'after_or_equal'       => __('The (%:attribute%) field must be a date after or equal to (:date).'),
            'alpha'                => __('The (%:attribute%) field must only contain letters.'),
            'alpha_dash'           => __('The (%:attribute%) field must only contain letters, numbers, dashes, and underscores.'),
            'alpha_num'            => __('The (%:attribute%) field must only contain letters and numbers.'),
            'array'                => __('The (%:attribute%) field must be an array.'),
            'ascii'                => __('The (%:attribute%) field must only contain single-byte alphanumeric characters and symbols.'),
            'before'               => __('The (%:attribute%) field must be a date before (:date).'),
            'before_or_equal'      => __('The (%:attribute%) field must be a date before or equal to (:date).'),
            'between'              => [
                'array'   => __('The (%:attribute%) field must have between (:min) and (:max) items.'),
                'file'    => __('The (%:attribute%) field must be between (:min) and (:max) kilobytes.'),
                'numeric' => __('The (%:attribute%) field must be between (:min) and (:max).'),
                'string'  => __('The (%:attribute%) field must be between (:min) and (:max) characters.'),
            ],
            'boolean'              => __('The (%:attribute%) field must be true or false.'),
            'can'                  => __('The (%:attribute%) field contains an unauthorized value.'),
            'confirmed'            => __('The (%:attribute%) field confirmation does not match.'),
            'current_password'     => __('The password is incorrect.'),
            'date'                 => __('The (%:attribute%) field must be a valid date.'),
            'date_equals'          => __('The (%:attribute%) field must be a date equal to (:date).'),
            'date_format'          => __('The (%:attribute%) field must match the format :format.'),
            'decimal'              => __('The (%:attribute%) field must have :decimal decimal places.'),
            'declined'             => __('The (%:attribute%) field must be declined.'),
            'declined_if'          => __('The (%:attribute%) field must be declined when (%:other%) is (:value).'),
            'different'            => __('The (%:attribute%) field and (%:other%) must be different.'),
            'digits'               => __('The (%:attribute%) field must be :digits digits.'),
            'digits_between'       => __('The (%:attribute%) field must be between (:min) and (:max) digits.'),
            'dimensions'           => __('The (%:attribute%) field has invalid image dimensions.'),
            'distinct'             => __('The (%:attribute%) field has a duplicate value.'),
            'doesnt_end_with'      => __('The (%:attribute%) field must not end with one of the following: (:values).'),
            'doesnt_start_with'    => __('The (%:attribute%) field must not start with one of the following: (:values).'),
            'email'                => __('The (%:attribute%) field must be a valid email address.'),
            'ends_with'            => __('The (%:attribute%) field must end with one of the following: (:values).'),
            'enum'                 => __('The selected (%:attribute%) is invalid.'),
            'exists'               => __('The selected (%:attribute%) is invalid.'),
            'file'                 => __('The (%:attribute%) field must be a file.'),
            'filled'               => __('The (%:attribute%) field must have a value.'),
            'gt'                   => [
                'array'   => __('The (%:attribute%) field must have more than (:value) items.'),
                'file'    => __('The (%:attribute%) field must be greater than (:value) kilobytes.'),
                'numeric' => __('The (%:attribute%) field must be greater than (:value).'),
                'string'  => __('The (%:attribute%) field must be greater than (:value) characters.'),
            ],
            'gte'                  => [
                'array'   => __('The (%:attribute%) field must have (:value) items or more.'),
                'file'    => __('The (%:attribute%) field must be greater than or equal to (:value) kilobytes.'),
                'numeric' => __('The (%:attribute%) field must be greater than or equal to (:value).'),
                'string'  => __('The (%:attribute%) field must be greater than or equal to (:value) characters.'),
            ],
            'image'                => __('The (%:attribute%) field must be an image.'),
            'in'                   => __('The selected (%:attribute%) is invalid.'),
            'in_array'             => __('The (%:attribute%) field must exist in (%:other%).'),
            'integer'              => __('The (%:attribute%) field must be an integer.'),
            'ip'                   => __('The (%:attribute%) field must be a valid IP address.'),
            'ipv4'                 => __('The (%:attribute%) field must be a valid IPv4 address.'),
            'ipv6'                 => __('The (%:attribute%) field must be a valid IPv6 address.'),
            'json'                 => __('The (%:attribute%) field must be a valid JSON string.'),
            'lowercase'            => __('The (%:attribute%) field must be lowercase.'),
            'lt'                   => [
                'array'   => __('The (%:attribute%) field must have less than (:value) items.'),
                'file'    => __('The (%:attribute%) field must be less than (:value) kilobytes.'),
                'numeric' => __('The (%:attribute%) field must be less than (:value).'),
                'string'  => __('The (%:attribute%) field must be less than (:value) characters.'),
            ],
            'lte'                  => [
                'array'   => __('The (%:attribute%) field must not have more than (:value) items.'),
                'file'    => __('The (%:attribute%) field must be less than or equal to (:value) kilobytes.'),
                'numeric' => __('The (%:attribute%) field must be less than or equal to (:value).'),
                'string'  => __('The (%:attribute%) field must be less than or equal to (:value) characters.'),
            ],
            'mac_address'          => __('The (%:attribute%) field must be a valid MAC address.'),
            'max'                  => [
                'array'   => __('The (%:attribute%) field must not have more than (:max) items.'),
                'file'    => __('The (%:attribute%) field must not be greater than (:max) kilobytes.'),
                'numeric' => __('The (%:attribute%) field must not be greater than (:max).'),
                'string'  => __('The (%:attribute%) field must not be greater than (:max) characters.'),
            ],
            'max_digits'           => __('The (%:attribute%) field must not have more than (:max) digits.'),
            'mimes'                => __('The (%:attribute%) field must be a file of type: (:values).'),
            'mimetypes'            => __('The (%:attribute%) field must be a file of type: (:values).'),
            'min'                  => [
                'array'   => __('The (%:attribute%) field must have at least (:min) items.'),
                'file'    => __('The (%:attribute%) field must be at least (:min) kilobytes.'),
                'numeric' => __('The (%:attribute%) field must be at least (:min).'),
                'string'  => __('The (%:attribute%) field must be at least (:min) characters.'),
            ],
            'min_digits'           => __('The (%:attribute%) field must have at least (:min) digits.'),
            'missing'              => __('The (%:attribute%) field must be missing.'),
            'missing_if'           => __('The (%:attribute%) field must be missing when (%:other%) is (:value).'),
            'missing_unless'       => __('The (%:attribute%) field must be missing unless (%:other%) is (:value).'),
            'missing_with'         => __('The (%:attribute%) field must be missing when (:values) is present.'),
            'missing_with_all'     => __('The (%:attribute%) field must be missing when (:values) are present.'),
            'multiple_of'          => __('The (%:attribute%) field must be a multiple of (:value).'),
            'not_in'               => __('The selected (%:attribute%) is invalid.'),
            'not_regex'            => __('The (%:attribute%) field format is invalid.'),
            'numeric'              => __('The (%:attribute%) field must be a number.'),
            'password'             => [
                'letters'       => __('The (%:attribute%) field must contain at least one letter.'),
                'mixed'         => __('The (%:attribute%) field must contain at least one uppercase and one lowercase letter.'),
                'numbers'       => __('The (%:attribute%) field must contain at least one number.'),
                'symbols'       => __('The (%:attribute%) field must contain at least one symbol.'),
                'uncompromised' => __('The given (%:attribute%) has appeared in a data leak. Please choose a different (%:attribute%).'),
            ],
            'present'              => __('The (%:attribute%) field must be present.'),
            'prohibited'           => __('The (%:attribute%) field is prohibited.'),
            'prohibited_if'        => __('The (%:attribute%) field is prohibited when (%:other%) is (:value).'),
            'prohibited_unless'    => __('The (%:attribute%) field is prohibited unless (%:other%) is in (:values).'),
            'prohibits'            => __('The (%:attribute%) field prohibits (%:other%) from being present.'),
            'regex'                => __('The (%:attribute%) field format is invalid.'),
            'required'             => __('The (%:attribute%) field is required.'),
            'required_array_keys'  => __('The (%:attribute%) field must contain entries for: (:values).'),
            'required_if'          => __('The (%:attribute%) field is required when (%:other%) is (:value).'),
            'required_if_accepted' => __('The (%:attribute%) field is required when (%:other%) is accepted.'),
            'required_unless'      => __('The (%:attribute%) field is required unless (%:other%) is in (:values).'),
            'required_with'        => __('The (%:attribute%) field is required when (:values) is present.'),
            'required_with_all'    => __('The (%:attribute%) field is required when (:values) are present.'),
            'required_without'     => __('The (%:attribute%) field is required when (:values) is not present.'),
            'required_without_all' => __('The (%:attribute%) field is required when none of (:values) are present.'),
            'same'                 => __('The (%:attribute%) field must match (%:other%).'),
            'size'                 => [
                'array'   => __('The (%:attribute%) field must contain (:size) items.'),
                'file'    => __('The (%:attribute%) field must be (:size) kilobytes.'),
                'numeric' => __('The (%:attribute%) field must be (:size).'),
                'string'  => __('The (%:attribute%) field must be (:size) characters.'),
            ],
            'starts_with'          => __('The (%:attribute%) field must start with one of the following: (:values).'),
            'string'               => __('The (%:attribute%) field must be a string.'),
            'timezone'             => __('The (%:attribute%) field must be a valid timezone.'),
            'unique'               => __('The (%:attribute%) has already been taken.'),
            'uploaded'             => __('The (%:attribute%) failed to upload.'),
            'uppercase'            => __('The (%:attribute%) field must be uppercase.'),
            'url'                  => __('The (%:attribute%) field must be a valid URL.'),
            'ulid'                 => __('The (%:attribute%) field must be a valid ULID.'),
            'uuid'                 => __('The (%:attribute%) field must be a valid UUID.'),
        ];
    }
}
